// S07d — fixture shared by the preview and the test file. Obviously fake
// figures for a fake contract, per CAPEX-01 §15. The four NHS ERIC bands
// (R12, R35), one funded, one overdue.
import type { Defect } from "@ecapital/shared";

export function buildDefects(): Defect[] {
  return [
    {
      id: "defect-1",
      orgUnitId: "larnaca-general",
      source: "HANDOVER",
      contractId: "contract-1",
      projectId: "project-1",
      areaId: "area-1",
      assetId: null,
      descriptionEl: "Διαρροή στη μόνωση οροφής του πλυντηρίου ασθενοφόρων",
      photoIds: [],
      estimatedCost: 18_500,
      riskBand: "HIGH",
      funded: true,
      targetProjectId: "project-2",
      status: "OPEN",
      raisedById: "user-engineer",
      raisedByName: "Ελένη Χριστοδούλου",
      raisedAt: "2026-06-01T09:00:00.000Z",
      dueDate: "2026-11-18",
      closedAt: null,
      closedById: null,
      closedByName: null,
    },
    {
      id: "defect-2",
      orgUnitId: "larnaca-general",
      source: "HANDOVER",
      contractId: "contract-1",
      projectId: "project-1",
      areaId: "area-unknown",
      assetId: null,
      descriptionEl: "Αστοχία στεγάνωσης στο δάπεδο του πλυντηρίου",
      photoIds: [],
      estimatedCost: 7_400,
      riskBand: "SIGNIFICANT",
      funded: false,
      targetProjectId: null,
      status: "IN_PROGRESS",
      raisedById: "user-engineer",
      raisedByName: "Ελένη Χριστοδούλου",
      raisedAt: "2026-06-02T09:00:00.000Z",
      dueDate: "2025-08-22",
      closedAt: null,
      closedById: null,
      closedByName: null,
    },
    {
      id: "defect-3",
      orgUnitId: "larnaca-general",
      source: "HANDOVER",
      contractId: "contract-1",
      projectId: "project-1",
      areaId: null,
      assetId: null,
      descriptionEl: "Ελλιπής σήμανση εξόδου κινδύνου στον διάδρομο",
      photoIds: [],
      estimatedCost: 1_200,
      riskBand: "MODERATE",
      funded: false,
      targetProjectId: null,
      status: "OPEN",
      raisedById: "user-engineer",
      raisedByName: "Ελένη Χριστοδούλου",
      raisedAt: "2026-06-03T09:00:00.000Z",
      dueDate: "2026-11-18",
      closedAt: null,
      closedById: null,
      closedByName: null,
    },
    {
      id: "defect-4",
      orgUnitId: "larnaca-general",
      source: "HANDOVER",
      contractId: "contract-1",
      projectId: "project-1",
      areaId: null,
      assetId: null,
      descriptionEl: "Φθορές βαφής στον προθάλαμο αναμονής",
      photoIds: [],
      estimatedCost: 450,
      riskBand: "LOW",
      funded: false,
      targetProjectId: null,
      status: "CLOSED",
      raisedById: "user-engineer",
      raisedByName: "Ελένη Χριστοδούλου",
      raisedAt: "2026-06-04T09:00:00.000Z",
      dueDate: "2026-11-18",
      closedAt: "2026-08-01T09:00:00.000Z",
      closedById: "user-engineer",
      closedByName: "Ελένη Χριστοδούλου",
    },
  ];
}
