import type { AppRole, Directorate, OrgUnit, OrgUnitType } from "@ecapital/shared";

// CAPEX-03 §3 — the eleven org units and the spellings column D of the capex
// plan uses for them. Values copied from apps/web/src/mocks/org-units.ts so
// the seeded API answers GET /org-units with exactly what the frontend mock
// answered (ADR-0005): the frontend swaps by base URL and sees no difference.
//
// Errata (docs/briefs/README.md): Troodos and Kyperounta are one hospital, so
// ΝΟΣΟΚΟΜΕΙΟ ΚΥΠΕΡΟΥΝΤΑΣ is an alias of Troodos, not a twelfth unit.

export interface SeedOrgUnit extends OrgUnit {
  aliases: string[];
}

const unit = (
  id: string,
  code: string,
  nameEl: string,
  nameEn: string,
  type: OrgUnitType,
  directorate: Directorate,
  costCentre: string,
  aliases: string[],
): SeedOrgUnit => ({
  id,
  code,
  nameEl,
  nameEn,
  type,
  directorate,
  costCentre,
  timezone: "Europe/Nicosia",
  aliases,
});

export const seedOrgUnits: SeedOrgUnit[] = [
  unit("nicosia-general", "NGH", "Γενικό Νοσοκομείο Λευκωσίας", "Nicosia General Hospital",
    "HOSPITAL", "LEFKOSIAS", "CC-NGH-01", ["Γ.Ν. ΛΕΥΚΩΣΙΑΣ"]),
  unit("larnaca-general", "LAR", "Γενικό Νοσοκομείο Λάρνακας", "Larnaca General Hospital",
    "HOSPITAL", "LARNAKAS_AMMOCHOSTOU", "CC-LAR-01", ["Γ.Ν. ΛΑΡΝΑΚΑΣ"]),
  unit("paphos-general", "PAF", "Γενικό Νοσοκομείο Πάφου", "Paphos General Hospital",
    "HOSPITAL", "LEMESOU_PAFOU", "CC-PAF-01", ["Γ.Ν. ΠΑΦΟΥ"]),
  unit("limassol-general", "LMS", "Γενικό Νοσοκομείο Λεμεσού", "Limassol General Hospital",
    "HOSPITAL", "LEMESOU_PAFOU", "CC-LMS-01", ["Γ.Ν. ΛΕΜΕΣΟΥ"]),
  unit("troodos", "TRD", "Νοσοκομείο Τροόδους", "Troodos Hospital",
    "HOSPITAL", "LEMESOU_PAFOU", "CC-TRD-01",
    ["ΝΟΣΟΚΟΜΕΙΟ ΤΡΟΟΔΟΥΣ", "ΝΟΣΟΚΟΜΕΙΟ ΚΥΠΕΡΟΥΝΤΑΣ", "Ν. ΚΥΠΕΡΟΥΝΤΑΣ"]),
  unit("namiii", "NAM3", "Νοσοκομείο Αρχιεπίσκοπος Μακάριος Γ΄", "Archbishop Makarios III Hospital",
    "HOSPITAL", "LEFKOSIAS", "CC-NAM3-01", ["ΝΑΜΙΙΙ"]),
  unit("polis-chrysochous", "PCH", "Νοσοκομείο Πόλεως Χρυσοχούς", "Polis Chrysochous Hospital",
    "HOSPITAL", "LEMESOU_PAFOU", "CC-PCH-01", ["ΝΟΣΟΚΟΜΕΙΟ ΠΟΛΕΩΣ ΧΡΥΣΟΧΟΥΣ"]),
  unit("famagusta-general", "FAM", "Γενικό Νοσοκομείο Αμμοχώστου", "Famagusta General Hospital",
    "HOSPITAL", "LARNAKAS_AMMOCHOSTOU", "CC-FAM-01", ["Γ.Ν. ΑΜΜΟΧΩΣΤΟΥ"]),
  unit("dypsy", "DYP", "Διεύθυνση Υπηρεσιών Ψυχικής Υγείας", "Mental Health Services",
    "SERVICE", "DYPSY", "CC-DYP-01", ["ΔΥΨΥ"]),
  unit("pfy", "PFY", "Πρωτοβάθμια Φροντίδα Υγείας", "Primary Healthcare",
    "SERVICE", "PFY", "CC-PFY-01", ["ΠΡΩΤΟΒΑΘΜΙΑ ΦΡΟΝΤΙΔΑ ΥΓΕΙΑΣ"]),
  unit("ambulance", "AMB", "Υπηρεσία Ασθενοφόρων", "Ambulance Service",
    "SERVICE", "AMBULANCE", "CC-AMB-01", ["ΥΠΗΡΕΣΙΑ ΑΣΘΕΝΟΦΟΡΩΝ"]),
];

// One building at Nicosia General with two floors and six areas, enough for
// the M0 area tree to have something in it on first run (§15). The risk
// groups follow ICRA 2.0 Table 2: theatre and ICU are the highest band, an
// inpatient ward is high, outpatients is medium, plant and office are low.
export const seedBuilding = {
  orgUnitId: "nicosia-general",
  code: "NGH-A",
  nameEl: "Κτίριο Α — Κεντρική Πτέρυγα",
  grossAreaM2: "18400.00",
  yearBuilt: 2006,
  storeys: 2,
  floors: [
    {
      code: "00",
      nameEl: "Ισόγειο",
      level: 0,
      areas: [
        {
          code: "OPD-01",
          nameEl: "Εξωτερικά Ιατρεία",
          areaType: "OPD" as const,
          patientRiskGroup: "MEDIUM" as const,
          costCentre: "CC-NGH-OPD",
          beds: null,
        },
        {
          code: "PLT-01",
          nameEl: "Μηχανοστάσιο",
          areaType: "PLANT" as const,
          patientRiskGroup: "LOW" as const,
          costCentre: "CC-NGH-TEC",
          beds: null,
        },
        {
          code: "OFF-01",
          nameEl: "Γραφεία Τεχνικών Υπηρεσιών",
          areaType: "OFFICE" as const,
          patientRiskGroup: "LOW" as const,
          costCentre: "CC-NGH-TEC",
          beds: null,
        },
      ],
    },
    {
      code: "01",
      nameEl: "Πρώτος όροφος",
      level: 1,
      areas: [
        {
          code: "THE-01",
          nameEl: "Χειρουργείο 1",
          areaType: "THEATRE" as const,
          patientRiskGroup: "HIGHEST" as const,
          costCentre: "CC-NGH-THE",
          beds: null,
        },
        {
          code: "ICU-01",
          nameEl: "Μονάδα Εντατικής Θεραπείας",
          areaType: "ICU" as const,
          patientRiskGroup: "HIGHEST" as const,
          costCentre: "CC-NGH-ICU",
          beds: 8,
        },
        {
          code: "WRD-01",
          nameEl: "Θάλαμος Α1",
          areaType: "WARD" as const,
          patientRiskGroup: "HIGH" as const,
          costCentre: "CC-NGH-WRD",
          beds: 24,
        },
      ],
    },
  ],
};

// Five users so every M0 access path has somebody to walk it. They exist only
// where DEV_AUTH is on; on the real server the users come from Entra ID.
export interface SeedUser {
  subject: string;
  name: string;
  email: string;
  roles: AppRole[];
  orgUnitIds: string[];
}

export const seedUsers: SeedUser[] = [
  {
    subject: "dev-admin",
    name: "Μαρία Κωνσταντίνου",
    email: "admin@ecapital.test",
    roles: ["admin"],
    // Central Administration carries every unit id, as the real token will.
    orgUnitIds: seedOrgUnits.map((u) => u.id),
  },
  {
    subject: "dev-estates-nicosia",
    name: "Ανδρέας Παπαδόπουλος",
    email: "estates.nicosia@ecapital.test",
    roles: ["estates_head"],
    orgUnitIds: ["nicosia-general"],
  },
  {
    subject: "dev-engineer-larnaca",
    name: "Ελένη Χριστοδούλου",
    email: "engineer.larnaca@ecapital.test",
    roles: ["project_engineer"],
    orgUnitIds: ["larnaca-general"],
  },
  {
    subject: "dev-clinical-nicosia",
    name: "Γιώργος Σάββα",
    email: "clinical.nicosia@ecapital.test",
    roles: ["clinical_approver"],
    orgUnitIds: ["nicosia-general"],
  },
  {
    subject: "dev-auditor",
    name: "Χριστίνα Λοΐζου",
    email: "auditor@ecapital.test",
    roles: ["auditor_readonly"],
    // The auditor sees every unit through the role, not through a list.
    orgUnitIds: [],
  },
  {
    subject: "dev-executive",
    name: "Ανδρέας Παπαδόπουλος",
    email: "executive@ecapital.test",
    roles: ["executive_readonly"],
    // Board and CEO office: every unit, read-only, like the auditor but
    // without access to the audit log.
    orgUnitIds: [],
  },
];

// Groups→roles is a config table, not code (ADR-0009). These are placeholder
// object ids; the ΟΚΥπΥ tenant's real group ids replace them at deployment.
export const seedRoleMappings: {
  entraGroupId: string;
  role: AppRole;
  orgUnitId: string | null;
  note: string;
}[] = [
  {
    entraGroupId: "00000000-0000-0000-0000-0000000000a1",
    role: "admin",
    orgUnitId: null,
    note: "eCapital Administrators",
  },
  {
    entraGroupId: "00000000-0000-0000-0000-0000000000a2",
    role: "executive_readonly",
    orgUnitId: null,
    note: "eCapital Executive",
  },
  {
    entraGroupId: "00000000-0000-0000-0000-0000000000a3",
    role: "auditor_readonly",
    orgUnitId: null,
    note: "eCapital Auditors",
  },
  {
    entraGroupId: "00000000-0000-0000-0000-0000000000b1",
    role: "estates_head",
    orgUnitId: "nicosia-general",
    note: "eCapital Estates — Nicosia General",
  },
  {
    entraGroupId: "00000000-0000-0000-0000-0000000000b2",
    role: "project_engineer",
    orgUnitId: "larnaca-general",
    note: "eCapital Engineers — Larnaca General",
  },
  {
    entraGroupId: "00000000-0000-0000-0000-0000000000b3",
    role: "clinical_approver",
    orgUnitId: "nicosia-general",
    note: "eCapital Clinical Approvers — Nicosia General",
  },
];


// ------------------------------------------------------------------- M1 --
// The 42 fixture projects, copied from apps/web/src/mocks/projects.ts so the
// seeded API answers GET /projects with what the frontend mock answered
// (ADR-0005). Copied and not imported: apps/api does not depend on apps/web,
// and a shared fixture would make the API's seed hostage to a frontend edit.
//
// Figures are obviously fake and round. `ref` is the fixture's own id, kept
// only so the two files can be compared by eye; the code each project ends up
// with is allocated by ecapital.allocate_project_code at seed time (ADR-0014),
// so it is NGH-2026-003 here and not the fixture's NGH-003.
//
// The natural key for a re-run is org unit + title (CAPEX-03 §2 col E), which
// is what makes `pnpm seed` safe to run twice.

export interface SeedProject {
  ref: string;
  orgUnitId: string;
  titleEl: string;
  category: "NEW_BUILD" | "RENOVATION" | "SMALL_WORKS" | "EQUIPMENT" | "MAINTENANCE_CAPITAL" | "IT";
  phase:
    | "IDEA"
    | "PREPARATION"
    | "APPROVED"
    | "TENDERED"
    | "AWARDED"
    | "IN_PROGRESS"
    | "PRACTICAL_COMPLETION"
    | "DEFECTS_LIABILITY"
    | "CLOSED";
  approvedBudget: number;
  fundingSource: "STATE_BUDGET" | "EU" | "DONATION" | "OWN";
  plannedStart: string | null;
  plannedFinish: string | null;
  rag: "GREEN" | "AMBER" | "RED";
  ragReason: string;
  sapWbs: string | null;
  tenderReference: string | null;
}

export const seedProjects: SeedProject[] = [
  {
    ref: "PRJ-001",
    orgUnitId: "polis-chrysochous",
    titleEl: "Ανακαίνιση χειρουργείων",
    category: "RENOVATION",
    phase: "IDEA",
    approvedBudget: 3115000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2027-03-13",
    plannedFinish: "2028-02-22",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-002",
    orgUnitId: "troodos",
    titleEl: "Αντικατάσταση ψυκτικών μονάδων",
    category: "MAINTENANCE_CAPITAL",
    phase: "IDEA",
    approvedBudget: 8915000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2027-02-11",
    plannedFinish: "2029-07-15",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-003",
    orgUnitId: "nicosia-general",
    titleEl: "Επέκταση ΤΑΕΠ",
    category: "NEW_BUILD",
    phase: "IDEA",
    approvedBudget: 10075000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2026-10-15",
    plannedFinish: "2027-12-08",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-004",
    orgUnitId: "namiii",
    titleEl: "Νέος μαγνητικός τομογράφος",
    category: "EQUIPMENT",
    phase: "IDEA",
    approvedBudget: 7310000,
    fundingSource: "EU",
    plannedStart: "2027-06-06",
    plannedFinish: "2028-03-20",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-005",
    orgUnitId: "nicosia-general",
    titleEl: "Αναβάθμιση συστήματος πυρανίχνευσης",
    category: "MAINTENANCE_CAPITAL",
    phase: "PREPARATION",
    approvedBudget: 1765000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2027-06-14",
    plannedFinish: "2028-10-06",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-006",
    orgUnitId: "pfy",
    titleEl: "Αντικατάσταση ανελκυστήρων",
    category: "MAINTENANCE_CAPITAL",
    phase: "PREPARATION",
    approvedBudget: 9245000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2027-06-30",
    plannedFinish: "2029-04-17",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-007",
    orgUnitId: "ambulance",
    titleEl: "Ανακαίνιση Μονάδας Εντατικής Θεραπείας",
    category: "RENOVATION",
    phase: "PREPARATION",
    approvedBudget: 6385000,
    fundingSource: "DONATION",
    plannedStart: "2027-10-04",
    plannedFinish: "2028-09-29",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-008",
    orgUnitId: "dypsy",
    titleEl: "Αναβάθμιση ηλεκτρομηχανολογικών εγκαταστάσεων",
    category: "MAINTENANCE_CAPITAL",
    phase: "PREPARATION",
    approvedBudget: 9315000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2027-05-02",
    plannedFinish: "2029-06-25",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-009",
    orgUnitId: "nicosia-general",
    titleEl: "Αντικατάσταση στέγης κτηρίου Γ",
    category: "MAINTENANCE_CAPITAL",
    phase: "PREPARATION",
    approvedBudget: 4750000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2027-02-25",
    plannedFinish: "2028-04-02",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-010",
    orgUnitId: "nicosia-general",
    titleEl: "Ενεργειακή αναβάθμιση κτηριακού συγκροτήματος",
    category: "RENOVATION",
    phase: "PREPARATION",
    approvedBudget: 4765000,
    fundingSource: "EU",
    plannedStart: "2026-11-18",
    plannedFinish: "2028-05-21",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-011",
    orgUnitId: "polis-chrysochous",
    titleEl: "Νέο ακτινολογικό μηχάνημα",
    category: "EQUIPMENT",
    phase: "PREPARATION",
    approvedBudget: 2400000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2027-07-14",
    plannedFinish: "2028-07-11",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-012",
    orgUnitId: "limassol-general",
    titleEl: "Αναβάθμιση δικτύου ιατρικών αερίων",
    category: "MAINTENANCE_CAPITAL",
    phase: "PREPARATION",
    approvedBudget: 7325000,
    fundingSource: "OWN",
    plannedStart: "2026-11-02",
    plannedFinish: "2028-05-01",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-013",
    orgUnitId: "pfy",
    titleEl: "Επέκταση χώρων στάθμευσης",
    category: "NEW_BUILD",
    phase: "PREPARATION",
    approvedBudget: 9595000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2027-06-24",
    plannedFinish: "2028-08-29",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-014",
    orgUnitId: "paphos-general",
    titleEl: "Ανακαίνιση εξωτερικών ιατρείων",
    category: "RENOVATION",
    phase: "PREPARATION",
    approvedBudget: 11745000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2027-02-20",
    plannedFinish: "2028-01-03",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-015",
    orgUnitId: "famagusta-general",
    titleEl: "Αντικατάσταση συστήματος κλιματισμού",
    category: "MAINTENANCE_CAPITAL",
    phase: "APPROVED",
    approvedBudget: 1290000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2026-12-01",
    plannedFinish: "2027-08-10",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-016",
    orgUnitId: "larnaca-general",
    titleEl: "Αναβάθμιση δικτύου πυρόσβεσης",
    category: "MAINTENANCE_CAPITAL",
    phase: "APPROVED",
    approvedBudget: 3345000,
    fundingSource: "EU",
    plannedStart: "2027-02-17",
    plannedFinish: "2028-02-04",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-017",
    orgUnitId: "troodos",
    titleEl: "Κατασκευή νέας πτέρυγας νοσηλείας",
    category: "NEW_BUILD",
    phase: "APPROVED",
    approvedBudget: 10125000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2026-10-09",
    plannedFinish: "2028-04-22",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-018",
    orgUnitId: "paphos-general",
    titleEl: "Αντικατάσταση ιατρικού εξοπλισμού εργαστηρίων",
    category: "EQUIPMENT",
    phase: "APPROVED",
    approvedBudget: 3025000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2027-05-26",
    plannedFinish: "2028-07-15",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-019",
    orgUnitId: "larnaca-general",
    titleEl: "Αναβάθμιση πληροφοριακού συστήματος νοσοκομείου",
    category: "IT",
    phase: "APPROVED",
    approvedBudget: 6565000,
    fundingSource: "DONATION",
    plannedStart: "2026-09-18",
    plannedFinish: "2027-10-18",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-020",
    orgUnitId: "nicosia-general",
    titleEl: "Επισκευή στέγης χειρουργικού τομέα",
    category: "MAINTENANCE_CAPITAL",
    phase: "APPROVED",
    approvedBudget: 11915000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2027-03-03",
    plannedFinish: "2028-05-14",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: null,
  },
  {
    ref: "PRJ-021",
    orgUnitId: "paphos-general",
    titleEl: "Αντικατάσταση λεβητοστασίου",
    category: "MAINTENANCE_CAPITAL",
    phase: "TENDERED",
    approvedBudget: 1225000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2026-11-23",
    plannedFinish: "2028-06-05",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: "TND-2026-021",
  },
  {
    ref: "PRJ-022",
    orgUnitId: "nicosia-general",
    titleEl: "Ανακαίνιση τμήματος αιμοκάθαρσης",
    category: "RENOVATION",
    phase: "TENDERED",
    approvedBudget: 2655000,
    fundingSource: "EU",
    plannedStart: "2026-10-29",
    plannedFinish: "2027-07-27",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: "TND-2026-022",
  },
  {
    ref: "PRJ-023",
    orgUnitId: "namiii",
    titleEl: "Αναβάθμιση συστήματος ελέγχου πρόσβασης",
    category: "MAINTENANCE_CAPITAL",
    phase: "TENDERED",
    approvedBudget: 1370000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2027-03-01",
    plannedFinish: "2028-09-02",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: "TND-2026-023",
  },
  {
    ref: "PRJ-024",
    orgUnitId: "limassol-general",
    titleEl: "Κατασκευή νέου ακτινοθεραπευτικού τμήματος",
    category: "NEW_BUILD",
    phase: "TENDERED",
    approvedBudget: 4515000,
    fundingSource: "OWN",
    plannedStart: "2027-01-15",
    plannedFinish: "2027-11-28",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: null,
    tenderReference: "TND-2026-024",
  },
  {
    ref: "PRJ-025",
    orgUnitId: "troodos",
    titleEl: "Αντικατάσταση δικτύου ύδρευσης",
    category: "MAINTENANCE_CAPITAL",
    phase: "AWARDED",
    approvedBudget: 1595000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2026-09-04",
    plannedFinish: "2027-06-05",
    rag: "RED",
    ragReason: "Η πρόβλεψη τελικού κόστους υπερβαίνει τον εγκεκριμένο προϋπολογισμό κατά €134.000",
    sapWbs: "WBS-TRD-025",
    tenderReference: "TND-2026-025",
  },
  {
    ref: "PRJ-026",
    orgUnitId: "limassol-general",
    titleEl: "Ανακαίνιση μαιευτηρίου",
    category: "RENOVATION",
    phase: "AWARDED",
    approvedBudget: 5560000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2026-08-19",
    plannedFinish: "2027-07-27",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: "WBS-LMS-026",
    tenderReference: "TND-2026-026",
  },
  {
    ref: "PRJ-027",
    orgUnitId: "paphos-general",
    titleEl: "Αναβάθμιση φαρμακείου νοσοκομείου",
    category: "SMALL_WORKS",
    phase: "AWARDED",
    approvedBudget: 1520000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2026-06-10",
    plannedFinish: "2027-05-29",
    rag: "AMBER",
    ragReason: "Οι δαπάνες υστερούν σημαντικά έναντι του χρονοδιαγράμματος του έργου",
    sapWbs: "WBS-PAF-027",
    tenderReference: "TND-2026-027",
  },
  {
    ref: "PRJ-028",
    orgUnitId: "dypsy",
    titleEl: "Επέκταση αποθηκευτικών χώρων",
    category: "NEW_BUILD",
    phase: "AWARDED",
    approvedBudget: 1470000,
    fundingSource: "EU",
    plannedStart: "2026-08-23",
    plannedFinish: "2027-11-23",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: "WBS-DYP-028",
    tenderReference: "TND-2026-028",
  },
  {
    ref: "PRJ-029",
    orgUnitId: "namiii",
    titleEl: "Νέο σύστημα αδιάλειπτης παροχής ενέργειας",
    category: "EQUIPMENT",
    phase: "IN_PROGRESS",
    approvedBudget: 11675000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2025-12-18",
    plannedFinish: "2026-10-16",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: "WBS-NAM3-029",
    tenderReference: "TND-2026-029",
  },
  {
    ref: "PRJ-030",
    orgUnitId: "dypsy",
    titleEl: "Αναβάθμιση κέντρου υγείας",
    category: "RENOVATION",
    phase: "IN_PROGRESS",
    approvedBudget: 10690000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2026-02-06",
    plannedFinish: "2027-10-13",
    rag: "RED",
    ragReason: "Οι δεσμεύσεις υπερβαίνουν τον εγκεκριμένο προϋπολογισμό κατά €1.702.000",
    sapWbs: "WBS-DYP-030",
    tenderReference: "TND-2026-030",
  },
  {
    ref: "PRJ-031",
    orgUnitId: "larnaca-general",
    titleEl: "Αντικατάσταση οχημάτων ασθενοφόρων",
    category: "EQUIPMENT",
    phase: "IN_PROGRESS",
    approvedBudget: 3320000,
    fundingSource: "DONATION",
    plannedStart: "2025-10-16",
    plannedFinish: "2026-10-01",
    rag: "RED",
    ragReason: "Η πρόβλεψη τελικού κόστους υπερβαίνει τον εγκεκριμένο προϋπολογισμό κατά €295.000",
    sapWbs: "WBS-LAR-031",
    tenderReference: "TND-2026-031",
  },
  {
    ref: "PRJ-032",
    orgUnitId: "polis-chrysochous",
    titleEl: "Ανακαίνιση σταθμού ασθενοφόρων",
    category: "RENOVATION",
    phase: "IN_PROGRESS",
    approvedBudget: 3460000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2025-12-03",
    plannedFinish: "2027-07-20",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: "WBS-PCH-032",
    tenderReference: "TND-2026-032",
  },
  {
    ref: "PRJ-033",
    orgUnitId: "paphos-general",
    titleEl: "Αναβάθμιση τηλεπικοινωνιακού εξοπλισμού",
    category: "IT",
    phase: "IN_PROGRESS",
    approvedBudget: 430000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2026-01-19",
    plannedFinish: "2026-12-07",
    rag: "RED",
    ragReason: "Η πρόβλεψη τελικού κόστους υπερβαίνει τον εγκεκριμένο προϋπολογισμό κατά €30.000",
    sapWbs: "WBS-PAF-033",
    tenderReference: "TND-2026-033",
  },
  {
    ref: "PRJ-034",
    orgUnitId: "limassol-general",
    titleEl: "Κατασκευή νέου κέντρου ψυχικής υγείας",
    category: "NEW_BUILD",
    phase: "IN_PROGRESS",
    approvedBudget: 6000000,
    fundingSource: "EU",
    plannedStart: "2025-03-22",
    plannedFinish: "2026-10-17",
    rag: "AMBER",
    ragReason: "Οι δαπάνες υστερούν σημαντικά έναντι του χρονοδιαγράμματος του έργου",
    sapWbs: "WBS-LMS-034",
    tenderReference: "TND-2026-034",
  },
  {
    ref: "PRJ-035",
    orgUnitId: "dypsy",
    titleEl: "Αναβάθμιση μονάδας ημερήσιας νοσηλείας",
    category: "SMALL_WORKS",
    phase: "IN_PROGRESS",
    approvedBudget: 7340000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2025-04-06",
    plannedFinish: "2026-09-03",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: "WBS-DYP-035",
    tenderReference: "TND-2026-035",
  },
  {
    ref: "PRJ-036",
    orgUnitId: "larnaca-general",
    titleEl: "Ανακαίνιση χειρουργείων",
    category: "RENOVATION",
    phase: "IN_PROGRESS",
    approvedBudget: 1535000,
    fundingSource: "OWN",
    plannedStart: "2025-10-19",
    plannedFinish: "2026-08-18",
    rag: "RED",
    ragReason: "Η πρόβλεψη τελικού κόστους υπερβαίνει τον εγκεκριμένο προϋπολογισμό κατά €110.000",
    sapWbs: "WBS-LAR-036",
    tenderReference: "TND-2026-036",
  },
  {
    ref: "PRJ-037",
    orgUnitId: "ambulance",
    titleEl: "Αντικατάσταση ψυκτικών μονάδων",
    category: "MAINTENANCE_CAPITAL",
    phase: "PRACTICAL_COMPLETION",
    approvedBudget: 1285000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2025-01-21",
    plannedFinish: "2025-12-19",
    rag: "RED",
    ragReason: "Οι δεσμεύσεις υπερβαίνουν τον εγκεκριμένο προϋπολογισμό κατά €171.000",
    sapWbs: "WBS-AMB-037",
    tenderReference: "TND-2026-037",
  },
  {
    ref: "PRJ-038",
    orgUnitId: "troodos",
    titleEl: "Επέκταση ΤΑΕΠ",
    category: "NEW_BUILD",
    phase: "PRACTICAL_COMPLETION",
    approvedBudget: 1350000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2025-03-25",
    plannedFinish: "2026-01-09",
    rag: "RED",
    ragReason: "Οι δεσμεύσεις υπερβαίνουν τον εγκεκριμένο προϋπολογισμό κατά €52.000",
    sapWbs: "WBS-TRD-038",
    tenderReference: "TND-2026-038",
  },
  {
    ref: "PRJ-039",
    orgUnitId: "limassol-general",
    titleEl: "Νέος μαγνητικός τομογράφος",
    category: "EQUIPMENT",
    phase: "DEFECTS_LIABILITY",
    approvedBudget: 4970000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2024-11-09",
    plannedFinish: "2025-11-18",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: "WBS-LMS-039",
    tenderReference: "TND-2026-039",
  },
  {
    ref: "PRJ-040",
    orgUnitId: "famagusta-general",
    titleEl: "Αναβάθμιση συστήματος πυρανίχνευσης",
    category: "MAINTENANCE_CAPITAL",
    phase: "DEFECTS_LIABILITY",
    approvedBudget: 4370000,
    fundingSource: "EU",
    plannedStart: "2025-03-08",
    plannedFinish: "2026-04-14",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: "WBS-FAM-040",
    tenderReference: "TND-2026-040",
  },
  {
    ref: "PRJ-041",
    orgUnitId: "nicosia-general",
    titleEl: "Αντικατάσταση ανελκυστήρων",
    category: "MAINTENANCE_CAPITAL",
    phase: "CLOSED",
    approvedBudget: 9160000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2023-11-21",
    plannedFinish: "2024-08-22",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: "WBS-NGH-041",
    tenderReference: "TND-2026-041",
  },
  {
    ref: "PRJ-042",
    orgUnitId: "larnaca-general",
    titleEl: "Ανακαίνιση Μονάδας Εντατικής Θεραπείας",
    category: "RENOVATION",
    phase: "CLOSED",
    approvedBudget: 3125000,
    fundingSource: "STATE_BUDGET",
    plannedStart: "2024-01-15",
    plannedFinish: "2024-11-25",
    rag: "GREEN",
    ragReason: "Το έργο βρίσκεται εντός εγκεκριμένου προϋπολογισμού και χρονοδιαγράμματος",
    sapWbs: "WBS-LAR-042",
    tenderReference: "TND-2026-042",
  },
];

// CAPEX-01 §15 wants every screen to have something in it on first run, and
// the S01 exceptions list is a screen. These three indices into seedProjects
// get a gate milestone whose forecast has slipped past its baseline — 45 days
// is amber, 120 and 200 are red — and these two lose their planned dates the
// way an imported row with an empty or text date cell does (CAPEX-03 V06).
// Two more projects are already overdue in the fixture itself (PRJ-035 and
// PRJ-036 are IN_PROGRESS with a planned finish behind us), so all three
// kinds of exception have something to say.
export const seedSlippedProjects: { index: number; slipDays: number }[] = [
  { index: 4, slipDays: 45 },
  { index: 16, slipDays: 120 },
  { index: 30, slipDays: 200 },
];
export const seedUndatedProjects = [9, 23];

/**
 * The gate that closes each phase, in phase order: entry `b` closes the
 * phase at index `b` of the nine (R04). A project that has moved past
 * boundary `b` has the gate ticked; the gate closing the phase it is in now
 * is still open, which is exactly what stops it moving on.
 */
export const seedGateTitles: string[] = [
  "Έγκριση ιδέας",
  "Έγκριση προϋπολογισμού",
  "Δημοσίευση διαγωνισμού",
  "Κατακύρωση διαγωνισμού",
  "Υπογραφή σύμβασης",
  "Ουσιαστική ολοκλήρωση",
  "Παράδοση χώρου στη μονάδα",
  "Λήξη περιόδου ευθύνης ελαττωμάτων",
];

/** Every project opens with this one, ungated, so even an idea has two lines. */
export const seedOpeningMilestone = "Προκαταρκτική εκτίμηση αναγκών";

/** Risks are dealt out of this pack, 0–3 per project (R07). */
export const seedRiskTexts: string[] = [
  "Καθυστέρηση στην έκδοση πολεοδομικής άδειας",
  "Αύξηση τιμών υλικών πάνω από την πρόβλεψη του προϋπολογισμού",
  "Περιορισμένη διαθεσιμότητα χώρου για εργασίες με τη μονάδα σε λειτουργία",
  "Ασυμβατότητα του εξοπλισμού με τις υπάρχουσες ηλεκτρομηχανολογικές εγκαταστάσεις",
  "Έλλειψη εξειδικευμένου προσωπικού για την επίβλεψη των εργασιών",
];

/** Issues likewise, 0–2 per project (R07). */
export const seedIssueTexts: string[] = [
  "Εκκρεμεί η απάντηση της Τεχνικής Υπηρεσίας στο αίτημα διευκρίνισης",
  "Το χρονοδιάγραμμα διακοπών ρεύματος δεν έχει συμφωνηθεί με τη μονάδα",
  "Δεν έχει οριστεί υπεύθυνος παραλαβής για τον νέο εξοπλισμό",
];
